stages:
  - test
  - build

variables:
  CI_CONFIG_FILE: 'public/env.js'
  CI_CONFIG: |
    window.API_URL = 'http://localhost/'
    window.AUTH_API_URL = 'http://localhost/'

include:
  - project: 'pretendent/devops/deploy'
    ref: 'master'
    file: 'ts-test-and-lint.yml'
  - project: 'pretendent/devops/deploy'
    ref: 'master'
    file: 'regular-build.yml'
