/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerFromJSON, AnswerToJSON, } from './';
export function AnswersFromJSON(json) {
    return AnswersFromJSONTyped(json, false);
}
export function AnswersFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'userGUID': json['userGUID'],
        'answers': (json['answers'].map(AnswerFromJSON)),
    };
}
export function AnswersToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'userGUID': value.userGUID,
        'answers': (value.answers.map(AnswerToJSON)),
    };
}
//# sourceMappingURL=Answers.js.map