/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CorrectAnswerFromJSON, CorrectAnswerToJSON, } from './';
export function CorrectAnswersFromJSON(json) {
    return CorrectAnswersFromJSONTyped(json, false);
}
export function CorrectAnswersFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'correctAnswers': (json['correct_answers'].map(CorrectAnswerFromJSON)),
    };
}
export function CorrectAnswersToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'correct_answers': (value.correctAnswers.map(CorrectAnswerToJSON)),
    };
}
//# sourceMappingURL=CorrectAnswers.js.map