/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export function QuestionsFromJSON(json) {
    return QuestionsFromJSONTyped(json, false);
}
export function QuestionsFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'orderNumber': json['order_number'],
        'code': json['code'],
        'question': json['question'],
        'answers': json['answers'],
    };
}
export function QuestionsToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'order_number': value.orderNumber,
        'code': value.code,
        'question': value.question,
        'answers': value.answers,
    };
}
//# sourceMappingURL=Questions.js.map