/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
export function UserFromJSON(json) {
    return UserFromJSONTyped(json, false);
}
export function UserFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': json['name'],
        'lastName': json['lastName'],
        'email': json['email'],
        'telegram': !exists(json, 'telegram') ? undefined : json['telegram'],
        'timeCreate': !exists(json, 'timeCreate') ? undefined : (new Date(json['timeCreate'])),
        'userGUID': !exists(json, 'userGUID') ? undefined : json['userGUID'],
    };
}
export function UserToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
        'lastName': value.lastName,
        'email': value.email,
        'telegram': value.telegram,
    };
}
//# sourceMappingURL=User.js.map