/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnswerFromJSON, AnswerToJSON, UserFromJSON, UserToJSON, } from './';
export function UserResultFromJSON(json) {
    return UserResultFromJSONTyped(json, false);
}
export function UserResultFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'user': UserFromJSON(json['user']),
        'percent': json['percent'],
        'answers': (json['answers'].map(AnswerFromJSON)),
    };
}
export function UserResultToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'user': UserToJSON(value.user),
        'answers': (value.answers.map(AnswerToJSON)),
    };
}
//# sourceMappingURL=UserResult.js.map