/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InlineObject6,
    InlineObject6FromJSON,
    InlineObject6ToJSON,
    InlineObject7,
    InlineObject7FromJSON,
    InlineObject7ToJSON,
    InlineObject8,
    InlineObject8FromJSON,
    InlineObject8ToJSON,
    InlineObject9,
    InlineObject9FromJSON,
    InlineObject9ToJSON,
    InlineResponse2002,
    InlineResponse2002FromJSON,
    InlineResponse2002ToJSON,
    InlineResponse2004,
    InlineResponse2004FromJSON,
    InlineResponse2004ToJSON,
    InlineResponse2005,
    InlineResponse2005FromJSON,
    InlineResponse2005ToJSON,
} from '../models';

export interface GroupsAddUserRequest {
    ident: string;
    inlineObject8: InlineObject8;
}

export interface GroupsCreateRequest {
    inlineObject6: InlineObject6;
}

export interface GroupsDeleteRequest {
    domain: string;
    ident: string;
}

export interface GroupsDeleteUserRequest {
    ident: string;
    inlineObject9: InlineObject9;
}

export interface GroupsGetRequest {
    domain: string;
    ident: string;
}

export interface GroupsGetAllRequest {
    domain: string;
    page?: number;
    limit?: number;
}

export interface GroupsGetUsersRequest {
    domain: string;
    ident: string;
    page?: number;
    limit?: number;
    blocked?: boolean;
}

export interface GroupsUpdateRequest {
    ident: string;
    inlineObject7?: InlineObject7;
}

/**
 * 
 */
export class GroupsApi extends runtime.BaseAPI {

    /**
     * add user to local domain group.  Allowed scopes:   - admin 
     */
    async groupsAddUserRaw(requestParameters: GroupsAddUserRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ident === null || requestParameters.ident === undefined) {
            throw new runtime.RequiredError('ident','Required parameter requestParameters.ident was null or undefined when calling groupsAddUser.');
        }

        if (requestParameters.inlineObject8 === null || requestParameters.inlineObject8 === undefined) {
            throw new runtime.RequiredError('inlineObject8','Required parameter requestParameters.inlineObject8 was null or undefined when calling groupsAddUser.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/_/{ident}/users`.replace(`{${"ident"}}`, encodeURIComponent(String(requestParameters.ident))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject8ToJSON(requestParameters.inlineObject8),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * add user to local domain group.  Allowed scopes:   - admin 
     */
    async groupsAddUser(requestParameters: GroupsAddUserRequest): Promise<void> {
        await this.groupsAddUserRaw(requestParameters);
    }

    /**
     * create group in local domain.  Allowed scopes:   - admin 
     */
    async groupsCreateRaw(requestParameters: GroupsCreateRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.inlineObject6 === null || requestParameters.inlineObject6 === undefined) {
            throw new runtime.RequiredError('inlineObject6','Required parameter requestParameters.inlineObject6 was null or undefined when calling groupsCreate.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/_`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject6ToJSON(requestParameters.inlineObject6),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * create group in local domain.  Allowed scopes:   - admin 
     */
    async groupsCreate(requestParameters: GroupsCreateRequest): Promise<void> {
        await this.groupsCreateRaw(requestParameters);
    }

    /**
     * delete group.  Allowed scopes:   - admin 
     */
    async groupsDeleteRaw(requestParameters: GroupsDeleteRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.domain === null || requestParameters.domain === undefined) {
            throw new runtime.RequiredError('domain','Required parameter requestParameters.domain was null or undefined when calling groupsDelete.');
        }

        if (requestParameters.ident === null || requestParameters.ident === undefined) {
            throw new runtime.RequiredError('ident','Required parameter requestParameters.ident was null or undefined when calling groupsDelete.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/{domain}/{ident}`.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters.domain))).replace(`{${"ident"}}`, encodeURIComponent(String(requestParameters.ident))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete group.  Allowed scopes:   - admin 
     */
    async groupsDelete(requestParameters: GroupsDeleteRequest): Promise<void> {
        await this.groupsDeleteRaw(requestParameters);
    }

    /**
     * delete user from local domain group.  Allowed scopes:   - admin 
     */
    async groupsDeleteUserRaw(requestParameters: GroupsDeleteUserRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ident === null || requestParameters.ident === undefined) {
            throw new runtime.RequiredError('ident','Required parameter requestParameters.ident was null or undefined when calling groupsDeleteUser.');
        }

        if (requestParameters.inlineObject9 === null || requestParameters.inlineObject9 === undefined) {
            throw new runtime.RequiredError('inlineObject9','Required parameter requestParameters.inlineObject9 was null or undefined when calling groupsDeleteUser.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/_/{ident}/users`.replace(`{${"ident"}}`, encodeURIComponent(String(requestParameters.ident))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject9ToJSON(requestParameters.inlineObject9),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete user from local domain group.  Allowed scopes:   - admin 
     */
    async groupsDeleteUser(requestParameters: GroupsDeleteUserRequest): Promise<void> {
        await this.groupsDeleteUserRaw(requestParameters);
    }

    /**
     * get specific groups.  Allowed scopes:   - admin   - self. Only groups that the user is member of 
     */
    async groupsGetRaw(requestParameters: GroupsGetRequest): Promise<runtime.ApiResponse<InlineResponse2005>> {
        if (requestParameters.domain === null || requestParameters.domain === undefined) {
            throw new runtime.RequiredError('domain','Required parameter requestParameters.domain was null or undefined when calling groupsGet.');
        }

        if (requestParameters.ident === null || requestParameters.ident === undefined) {
            throw new runtime.RequiredError('ident','Required parameter requestParameters.ident was null or undefined when calling groupsGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/{domain}/{ident}`.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters.domain))).replace(`{${"ident"}}`, encodeURIComponent(String(requestParameters.ident))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2005FromJSON(jsonValue));
    }

    /**
     * get specific groups.  Allowed scopes:   - admin   - self. Only groups that the user is member of 
     */
    async groupsGet(requestParameters: GroupsGetRequest): Promise<InlineResponse2005> {
        const response = await this.groupsGetRaw(requestParameters);
        return await response.value();
    }

    /**
     * get groups.  Allowed scopes:   - admin 
     */
    async groupsGetAllRaw(requestParameters: GroupsGetAllRequest): Promise<runtime.ApiResponse<InlineResponse2004>> {
        if (requestParameters.domain === null || requestParameters.domain === undefined) {
            throw new runtime.RequiredError('domain','Required parameter requestParameters.domain was null or undefined when calling groupsGetAll.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        } else if( window.localStorage.getItem( 'access_token' ) ){
            queryParameters["access_token"] = window.localStorage.getItem( 'access_token' )
        }

        const response = await this.request({
            path: `/groups/{domain}`.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters.domain))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2004FromJSON(jsonValue));
    }

    /**
     * get groups.  Allowed scopes:   - admin 
     */
    async groupsGetAll(requestParameters: GroupsGetAllRequest): Promise<InlineResponse2004> {
        const response = await this.groupsGetAllRaw(requestParameters);
        return await response.value();
    }

    /**
     * get all group users.  Allowed scopes:   - admin 
     */
    async groupsGetUsersRaw(requestParameters: GroupsGetUsersRequest): Promise<runtime.ApiResponse<InlineResponse2002>> {
        if (requestParameters.domain === null || requestParameters.domain === undefined) {
            throw new runtime.RequiredError('domain','Required parameter requestParameters.domain was null or undefined when calling groupsGetUsers.');
        }

        if (requestParameters.ident === null || requestParameters.ident === undefined) {
            throw new runtime.RequiredError('ident','Required parameter requestParameters.ident was null or undefined when calling groupsGetUsers.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.blocked !== undefined) {
            queryParameters['blocked'] = requestParameters.blocked;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/{domain}/{ident}/users`.replace(`{${"domain"}}`, encodeURIComponent(String(requestParameters.domain))).replace(`{${"ident"}}`, encodeURIComponent(String(requestParameters.ident))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineResponse2002FromJSON(jsonValue));
    }

    /**
     * get all group users.  Allowed scopes:   - admin 
     */
    async groupsGetUsers(requestParameters: GroupsGetUsersRequest): Promise<InlineResponse2002> {
        const response = await this.groupsGetUsersRaw(requestParameters);
        return await response.value();
    }

    /**
     * change group in local domain.  Allowed scopes:   - admin 
     */
    async groupsUpdateRaw(requestParameters: GroupsUpdateRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ident === null || requestParameters.ident === undefined) {
            throw new runtime.RequiredError('ident','Required parameter requestParameters.ident was null or undefined when calling groupsUpdate.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // AccessToken authentication
        }

        const response = await this.request({
            path: `/groups/_/{ident}`.replace(`{${"ident"}}`, encodeURIComponent(String(requestParameters.ident))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject7ToJSON(requestParameters.inlineObject7),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * change group in local domain.  Allowed scopes:   - admin 
     */
    async groupsUpdate(requestParameters: GroupsUpdateRequest): Promise<void> {
        await this.groupsUpdateRaw(requestParameters);
    }

}
