export const SET_DEFAULT_DATA = 'setDefaultUserData'
export const SET_DOMAINS = 'setDomains'
export const SET_AFTER_LOGIN = 'setAfterLogin'
export const SET_USER = 'setUser'
export const SET_STATUS = 'setStatus'
export const SET_MESSAGE = 'setMessage'
export const SET_ALLOWED_PERMITS = 'setAllowedPermits'
