/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ADFS
 */
export interface ADFS {
    /**
     * token that was obtained from ADFS using /auth/{domain}/signin
     * @type {string}
     * @memberof ADFS
     */
    token: string;
    /**
     * state that was passed to /auth/{domain}/signin
     * @type {string}
     * @memberof ADFS
     */
    state: string;
}

export function ADFSFromJSON(json: any): ADFS {
    return ADFSFromJSONTyped(json, false);
}

export function ADFSFromJSONTyped(json: any, ignoreDiscriminator: boolean): ADFS {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'token': json['token'],
        'state': json['state'],
    };
}

export function ADFSToJSON(value?: ADFS | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'token': value.token,
        'state': value.state,
    };
}


