/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 1 - internal API error
     * 2 - bad request
     * 3 - unauthorized
     * 1001 - internal DB error
     * 1002 - already exists
     * 1003 - wrong password
     * 1004 - invalid argument
     * 1005 - not found
     * 1006 - protected
     * 2001 - internal domain error
     * 2002 - bad request
     * 2003 - wrong password
     * @type {number}
     * @memberof ErrorResponse
     */
    errorCode?: number;
    /**
     *
     * @type {string}
     * @memberof ErrorResponse
     */
    errorMsg?: string;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'errorMsg': !exists(json, 'error_msg') ? undefined : json['error_msg'],
    };
}

export function ErrorResponseToJSON(value?: ErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'error_code': value.errorCode,
        'error_msg': value.errorMsg,
    };
}


