/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InlineObject5
 */
export interface InlineObject5 {
    /**
     * required if you don't have admin permissions
     * @type {string}
     * @memberof InlineObject5
     */
    password?: string;
    /**
     * must be at least 8 symbols long
     * @type {string}
     * @memberof InlineObject5
     */
    newPassword?: string;
    /**
     *
     * @type {string}
     * @memberof InlineObject5
     */
    displayName?: string;
}

export function InlineObject5FromJSON(json: any): InlineObject5 {
    return InlineObject5FromJSONTyped(json, false);
}

export function InlineObject5FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject5 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'password': !exists(json, 'password') ? undefined : json['password'],
        'newPassword': !exists(json, 'new_password') ? undefined : json['new_password'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
    };
}

export function InlineObject5ToJSON(value?: InlineObject5 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'password': value.password,
        'new_password': value.newPassword,
        'display_name': value.displayName,
    };
}


