/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3 {
    /**
     * arbitrary string to track this logout session
     * @type {string}
     * @memberof InlineObject3
     */
    state: string;
    /**
     * upon completion user will be redirected to this URL. Query params will contain the result.
     * On success they will have 'state' param that was passed earlier. You can use it to make sure
     * that redirect is part of the same logout session.
     * On failure they will have 'error' param containing JSON string with ErrorResponse object
     * explaining the error. If failure happens due to ADFS, refresh token is still invalidated.
     * @type {string}
     * @memberof InlineObject3
     */
    redirect: string;
    /**
     *
     * @type {string}
     * @memberof InlineObject3
     */
    refreshToken: string;
}

export function InlineObject3FromJSON(json: any): InlineObject3 {
    return InlineObject3FromJSONTyped(json, false);
}

export function InlineObject3FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject3 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'state': json['state'],
        'redirect': json['redirect'],
        'refreshToken': json['refresh_token'],
    };
}

export function InlineObject3ToJSON(value?: InlineObject3 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'state': value.state,
        'redirect': value.redirect,
        'refresh_token': value.refreshToken,
    };
}


