/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
export function UserFromJSON(json) {
    return UserFromJSONTyped(json, false);
}
export function UserFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'login': !exists(json, 'login') ? undefined : json['login'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'blocked': !exists(json, 'blocked') ? undefined : json['blocked'],
        '_protected': !exists(json, 'protected') ? undefined : json['protected'],
    };
}
export function UserToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'domain': value.domain,
        'login': value.login,
        'display_name': value.displayName,
        'blocked': value.blocked,
        'protected': value._protected,
    };
}
//# sourceMappingURL=User.js.map