/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists } from '../runtime';
import { GroupFromJSON, GroupToJSON, KVFromJSON, KVToJSON, } from './';
export function UserFullFromJSON(json) {
    return UserFullFromJSONTyped(json, false);
}
export function UserFullFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'login': !exists(json, 'login') ? undefined : json['login'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'blocked': !exists(json, 'blocked') ? undefined : json['blocked'],
        'groups': !exists(json, 'groups') ? undefined : (json['groups'].map(GroupFromJSON)),
        'kv': !exists(json, 'kv') ? undefined : (json['kv'].map(KVFromJSON)),
        '_protected': !exists(json, 'protected') ? undefined : json['protected'],
    };
}
export function UserFullToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'domain': value.domain,
        'login': value.login,
        'display_name': value.displayName,
        'blocked': value.blocked,
        'groups': value.groups === undefined ? undefined : (value.groups.map(GroupToJSON)),
        'kv': value.kv === undefined ? undefined : (value.kv.map(KVToJSON)),
        'protected': value._protected,
    };
}
//# sourceMappingURL=UserFull.js.map