/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Message,
    MessageFromJSON,
    MessageToJSON,
    Results,
    ResultsFromJSON,
    ResultsToJSON,
} from '../models';

export interface ResultsRequest {
    offset?: number;
    limit?: number;
}

/**
 * 
 */
export class ResultsApi extends runtime.BaseAPI {

    /**
     * Results users with their answers
     */
    async resultsRaw(requestParameters: ResultsRequest): Promise<runtime.ApiResponse<Results>> {
        const queryParameters: any = {};

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/results`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultsFromJSON(jsonValue));
    }

    /**
     * Results users with their answers
     */
    async results(requestParameters: ResultsRequest): Promise<Results> {
        const response = await this.resultsRaw(requestParameters);
        return await response.value();
    }

}
