/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ResultsFromJSON, } from '../models';
/**
 *
 */
export class ResultsApi extends runtime.BaseAPI {
    /**
     * Results users with their answers
     */
    async resultsRaw(requestParameters) {
        const queryParameters = {};
        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }
        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }
        const headerParameters = {};
        const response = await this.request({
            path: `/results`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
        return new runtime.JSONApiResponse(response, (jsonValue) => ResultsFromJSON(jsonValue));
    }
    /**
     * Results users with their answers
     */
    async results(requestParameters) {
        const response = await this.resultsRaw(requestParameters);
        return await response.value();
    }
}
//# sourceMappingURL=ResultsApi.js.map