/* tslint:disable */
/* eslint-disable */
/**
 * Pretendent backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { UserFromJSON, UserToJSON, } from '../models';
/**
 *
 */
export class UserApi extends runtime.BaseAPI {
    /**
     * Create user
     */
    async usersCreateRaw(requestParameters) {
        if (requestParameters.user === null || requestParameters.user === undefined) {
            throw new runtime.RequiredError('user', 'Required parameter requestParameters.user was null or undefined when calling usersCreate.');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        const response = await this.request({
            path: `/user`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserToJSON(requestParameters.user),
        });
        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }
    /**
     * Create user
     */
    async usersCreate(requestParameters) {
        const response = await this.usersCreateRaw(requestParameters);
        return await response.value();
    }
}
//# sourceMappingURL=UserApi.js.map