/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
    login: string;
    /**
     * must be at least 8 symbols long
     * @type {string}
     * @memberof InlineObject4
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
    displayName?: string;
}

export function InlineObject4FromJSON(json: any): InlineObject4 {
    return InlineObject4FromJSONTyped(json, false);
}

export function InlineObject4FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject4 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
    };
}

export function InlineObject4ToJSON(value?: InlineObject4 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'password': value.password,
        'display_name': value.displayName,
    };
}


