/* tslint:disable */
/* eslint-disable */
/**
 * okauth
 * For authorization this spec uses scopes:   - admin. Read/write access to everything. Requires valid access_token and secure_okauth_admin=true KV   - self. Access permissions are method specific. Requires valid access_token  Other scopes are method specific 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * domain name the user is part of
     * @type {string}
     * @memberof User
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    login?: string;
    /**
     * human friendly name
     * @type {string}
     * @memberof User
     */
    displayName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    blocked?: boolean;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'domain': !exists(json, 'domain') ? undefined : json['domain'],
        'login': !exists(json, 'login') ? undefined : json['login'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'blocked': !exists(json, 'blocked') ? undefined : json['blocked'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'domain': value.domain,
        'login': value.login,
        'display_name': value.displayName,
        'blocked': value.blocked,
    };
}


